### Виконати набір вправ
* **Завдання 1.** Вводиться число n. Вивести масив разміра nхn, в якому по діагоналі йдуть числа від 1 до n, а інші числа рівні 0
* **Завдання 5.** Вводиться число n. Вивести масив розміру n на n, в якому в рядках з парними індексами стоять 1, а в інших – 0. 
* **Завдання 9.** Вводиться число n. Створити масив значень від n до 0.
* **Завдання 10.** Вводиться числа n i m. Створити масив випадкових значень n на m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми.
* **Завдання 12.** Створити масив одиниць розміром n х n та створити в ньому«рамку», сформовану з 0.
* **Завдання 15.** Розмістити на полі 8х8 0 та одиниці в шахматному порядку, використовуючи функцію numpy tile().
* **Завдання 16.** Заповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.
* **Завдання 21.** Згенерувати вектор із n випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.
* **Завдання 22.** Ввести числа n і m. Згенерувати матрицю n на n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.
### Розв’язати систему за допомогою формул Крамера і виконати перевірку за допомогою:
*  **матричного множення;**
    * Нехай для матриці $А$ порядку $n на n$ існує зворотна матриця $A^{-1}$. Помножимо обидві частини матричного рівняння $A ⋅ X =В$ зліва на $A^{-1}$ (порядки матриць $A ⋅ X =В$ дозволяють зробити таку операцію, дивіться статтю операції над матрицями, властивості операцій). Маємо $A^{-1}(A ⋅ X) =A^{-1}⋅ B$. Так як для операції множення матриць відповідних порядків характерно властивість асоціативності, то останню рівність можна переписати як $(A^{-1}⋅A) ⋅ X =A^{-1}⋅ B$, а за визначенням оберненої матриці $A^{-1}⋅A = E$ ($E$- одинична матриця порядку $n на n$), тому
$$(A^{-1}⋅A) ⋅ X =A^{-1}⋅ B$$
$$E⋅X = A^{-1}⋅A $$
$$X =A^{-1}⋅B$$
      Таким чином, рішення системи лінійних алгебраїчних рівнянь матричним методом визначається за формулою $X =A^{-1}⋅B$ . Іншими словами, рішення СЛАР знаходиться за допомогою оберненої матриці $A^{-1}$.
* **функції numpy.linalg.solve().**
### Рішення з допомогою формул Крамера
Метод Крамера полягає в тому, що ми послідовно знаходимо головний визначник системи (5.1), тобто визначник матриці $А$

$$D = det (ai j)$$

   і $n$ допоміжних визначників $D$ i $(i = 1, ..., n)$, які виходять з визначника $D$ заміною $i-го$ стовпця стовпцем вільних членів.

   Формули Крамера мають вигляд:

$$D × x i = D i (i = 1, ..., n). (5.2)$$

   З (5.2) випливає правило Крамера, яке дає вичерпну відповідь на питання про спільності системи (5.1): якщо головний визначник системи відмінний від нуля, то система має єдине рішення, яке визначається за формулами:

$$x i = D i / D.$$

   Якщо головний визначник системи $D$ і всі допоміжні визначники $D i = 0 (i = 1, ..., n)$, то система має безліч рішень. Якщо головний визначник системи $D = 0$, а хоча б один допоміжний визначник відмінний від нуля, то система несумісна.
### Обчислити значення матричного виразу.
Дано матричні рівняння:
        $$AA·X = B, (1)$$
        $$Y·A = B, (2)$$
де $A$ і $B$ - задані матриці, причому $A$ - невироджена. Потрібно знайти       матриці $X$ і $Y$.
Згадаємо, що в числовій області частка від ділення b на a визначається як рішення рівняння $a ∙ x = b$ $(або x ∙ a = b)$ і існує не завжди. Можна спробувати визначити «поділ» матриць, розглядаючи рівняння (1) і (2), в яких, згідно з правилом множення, матриці $A, B, X, Y$ не можуть мати довільну структуру. Так, в першому рівнянні матриці A і B повинні мати однакове число рядків, а в другому - однакове число стовпців. Вже звідси ясно, що якщо навіть обидва ці рівняння однозначно розв'язні (а це далеко не завжди так), то їх рішення цілком можуть бути матрицями не тільки різними, але і різної структури. Таким чином, для матриць виявляється неможливим визначити розподіл зі звичними властивостями. Матричні рівняння виду (1) і (2) вирішуються наступним чином. Так як A невироджена матриця, то існує обернена матриця A-1. Помножимо зліва обидві частини рівняння (1) на $A^{-1}$: $A^{-1} · A · X = A^{-1} · B$, тоді отримаємо $E · X = A^{-1} $· B, або $$X = A^{-1}$$ · B. (3) Аналогічно, множачи справа обидві частини рівності (2) на$ A^{-1}$, будемо мати: $Y · A · A^{-1} = B · A^{-1}$, звідки знаходимо, що $$Y = B · A^{-1}. (4)$$
### Розв’язати рівняння за допомогою оберненої матриці і виконати перевірку за допомогою:
*  **матричного множення;**
* **функції numpy.linalg.solve().**

In [268]:
print("Задание №1\nВводиться число n. Вивести масив разміра nхn, в якому по діагоналі йдуть числа від 1 до n, а інші числа рівні 0")
import numpy as np
n = int(input("> "))
Z = np.diag(np.linspace(1, n, n,dtype = int))
print(Z)  

Задание №1
Вводиться число n. Вивести масив разміра nхn, в якому по діагоналі йдуть числа від 1 до n, а інші числа рівні 0
> 5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [269]:
print("Задание №5\nВводиться число n. Вивести масив розміру n на n, в якому в рядках з парними індексами стоять 1, а в інших – 0.")
import numpy as np
n = int(input("> "))
Z = np.zeros((n,n), dtype=int)
Z[::2,:] = 1
print(Z)

Задание №5
Вводиться число n. Вивести масив розміру n на n, в якому в рядках з парними індексами стоять 1, а в інших – 0.
> 5
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [262]:
print("Задание №9\nВводиться число n. Створити масив значень від n до 0.")
import numpy as np
n = int(input("> "))
Z = np.arange(0, n+1, 1)
print(Z[::-1])

Задание №9
  Вводиться число n. Створити масив значень від n до 0.
> 5
[5 4 3 2 1 0]


In [264]:
print("Задание №10\nВводиться числа n i m. Створити масив випадкових значень n на m \n і обчислити мінімальне, максимальне значення, середнє та середньоквадратичне\n відхилення, округлене до 3 знаків після коми")
import numpy as np
n = int(input())
m = int(input())
a = np.random.choice(np.arange(1, 92), size=(n,m), replace=False)
z=np.random.random((n, m))
print("Масив цілих чисел\n",a)
print("Mінімум: ",np.round(np.amin(a),3))
print("Максимум: ",np.round(np.amax(a),3))
print("Середнє значення: ",np.round(np.mean(a),3))
print("Дисперсія ",np.round(np.var(a),3))
print("\nМасив чисел від 0 до 1\n",z)
print("Mінімум: ",np.round(np.amin(z),3))
print("Максимум: ",np.round(np.amax(z),3))
print("Середнє значення: ",np.round(np.mean(z),3))
print("Дисперсія: ",np.round(np.var(z),3))

Задание №10
Вводиться числа n i m. Створити масив випадкових значень n на m 
 і обчислити мінімальне, максимальне значення, середнє та середньоквадратичне
 відхилення, округлене до 3 знаків після коми
5
4
Масив цілих чисел
 [[77 58 14 53]
 [76 66 51 37]
 [61 86 40 85]
 [52 23 50 35]
 [71  9  7 82]]
Mінімум:  7
Максимум:  86
Середнє значення:  51.65
Дисперсія  592.027

Масив чисел від 0 до 1
 [[0.80631906 0.17733002 0.4045918  0.24550989]
 [0.63840927 0.1948466  0.83924405 0.65438914]
 [0.63177772 0.77254539 0.75540387 0.13786085]
 [0.58981837 0.44185067 0.11025587 0.65370018]
 [0.0217366  0.41223622 0.42774126 0.8590878 ]]
Mінімум:  0.022
Максимум:  0.859
Середнє значення:  0.489
Дисперсія:  0.068


In [270]:
print("Задание №12\n Створити масив одиниць розміром n х n та створити в ньому«рамку», сформовану з 0.")
import numpy as np
n = int(input())
Z = np.ones((n,n), dtype=int)
Z[0::n-1,:] = 0
Z[:,0::n-1] = 0
print(Z)

Задание №12
 Створити масив одиниць розміром n х n та створити в ньому«рамку», сформовану з 0.
4
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [73]:
print("Задание №15\nРозмістити на полі 8х8 0 та одиниці в шахматному порядку,використовуючи функцію numpy tile().")
import numpy as np
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

Задание №15
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [271]:
print("Задание №14\nРозмістити на полі 8х8 0 та одиниці в шахматному порядку,використовуючи функцію повторення (*).")
import numpy as np
Z = np.repeat(np.array([[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0]]),1,axis=0)
print(Z)
#print(z)

Задание №14
Розмістити на полі 8х8 0 та одиниці в шахматному порядку,використовуючи функцію повторення (*).
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [272]:
print("Задание №16\nЗаповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.")
import numpy as np
n = int(input())
Z = np.zeros((n,n), dtype=int)
Z[:,1::2] = 1
print(Z)

Задание №16
Заповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.
5
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


In [225]:
print("Задание №21\n Згенерувати вектор із n випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.")
import numpy as np
n = int(input())
z=np.random.random(n)
print(z)
#max = np.amax(z)
#print("Max",max)
#s = 0
#for x in range(len(z)):
#    if z[x] > s:
#        s = z[x]
   #     b = x
#z[b]=0
print("Max",z[z.argmax()])
z[z.argmax()] = 0
print(z)

Задание №21
5
[0.5716597  0.2300146  0.77277449 0.36079699 0.11410696]
Max 0.7727744905903701
[0.5716597  0.2300146  0.         0.36079699 0.11410696]


In [265]:
print("Задание №22\n  Ввести числа n і m. Згенерувати матрицю n на n випадкових цілихелементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриціна протилежні за знаком.")
import numpy as np
n = int(input())
m = int(input())
z=np.random.randint(0, m, (n, m))
max = np.amax(z)
print(z)
print(np.where(z == max,max*(-1), z))

Задание №22
  Ввести числа n і m. Згенерувати матрицю n на n випадкових цілихелементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриціна протилежні за знаком.
5
4
[[3 3 2 2]
 [2 3 2 2]
 [2 3 1 3]
 [1 0 1 0]
 [2 3 1 0]]
[[-3 -3  2  2]
 [ 2 -3  2  2]
 [ 2 -3  1 -3]
 [ 1  0  1  0]
 [ 2 -3  1  0]]


In [273]:
print("Матричний вираз")
import numpy as np
A = np.matrix('1 0 3; -2 0 1; -1 3 1')
B = np.matrix('2 0 2; 5 -7 -2; 1 0 -1')
print("(2*A - B)*(3*A+B)-2*A*B")
print(3*A - (A-2*B)*B)

Матричний вираз
(2*A - B)*(3*A+B)-2*A*B
[[ 10   0  14]
 [-57  98  60]
 [-15  30  18]]


In [267]:
print("Крамер")
import numpy
A= numpy.array([[2,-1, 1, -1], [2, -1, 0, -3], [3, 0, -1, 1],[2, 2, -2, 5]]) # Матрица (левая часть системы)
B = numpy.array([1, 2, -3,-6]) # Вектор (правая часть системы)
print("Матричне множення")
Aob = numpy.linalg.inv(A)
print("Обратная матрица \n",Aob,"\n")
print("X= B*A^(-1) \n",(Aob.dot(B)),"\n")
print(" numpy.linalg.solve().")
numpy.linalg.solve(A, B)
np.allclose((Aob.dot(B)), np.linalg.solve(A, B), rtol=0, atol=1e-7)

Крамер
Матричне множення
Обратная матрица 
 [[ 3.33333333e-01  3.33333333e-01 -3.33333333e-01  3.33333333e-01]
 [ 6.66666667e-01  1.66666667e+00 -2.66666667e+00  1.66666667e+00]
 [ 1.00000000e+00  3.33333333e-01 -1.33333333e+00  6.66666667e-01]
 [-7.40148683e-17 -6.66666667e-01  6.66666667e-01 -3.33333333e-01]] 

X= B*A^(-1) 
 [ 0.          2.          1.66666667 -1.33333333] 

 numpy.linalg.solve().


True

In [266]:
import numpy as np
print("Розв’язати рівняння ")
A = np.array([[5, -1, 3], [0, 2, -1], [-2, -1, 0]])
B = np.array([[3, 7, -2], [1, 1, -2], [0, 1, 3]]) 
print("Матричне множення")
print("A= \n",A,"\n")
print("B= \n",B,"\n")
detA = np.linalg.det(A)
print("Det",detA)
a11 = A[1,1]*A[2,2]-A[2,1]*A[1,2]
a12 = -1*(A[1,0]*A[2,2]-A[2,0]*A[1,2])
a13 = A[1,0]*A[2,1]-A[2,0]*A[1,1]
a21 = -1*(A[0,1]*A[2,2]-A[2,1]*A[0,2])
a22 = A[0,0]*A[2,2]-A[2,0]*A[0,2]
a23 = -1*(A[0,0]*A[2,1]-A[2,0]*A[0,1])
a31 = A[0,1]*A[1,2]-A[1,1]*A[0,2]
a32 = -1*(A[0,0]*A[1,2]-A[1,0]*A[0,2])
a33 = A[0,0]*A[1,1]-A[1,0]*A[0,1]
Ad = np.array([[a11,a12,a13],[a21,a22,a23],[a31,a32,a33]])
print("Матрица алгебраических дополнений\n",Ad)
At = Ad.transpose()
print("Транспонированная матрица\n",At)
Aob1 = (1/5)*At
print("Обратная матрица(Вручную)(At*(1/5))\n",Aob1,"\n")
Aob2 = numpy.linalg.inv(A)
print("Обратная матрица (numpy.linalg.inv())\n",Aob2,"\n")
print("(Вручную) X= B*A^(-1) \n",Aob1.dot(B))
print("X= B*A^(-1) \n",Aob2.dot(B))
print("\n numpy.linalg.solve().")
print("X= \n",np.linalg.solve(A, B))
np.allclose(Aob2.dot(B), np.linalg.solve(A, B), rtol=0, atol=1e-7)

Розв’язати рівняння 
Матричне множення
A= 
 [[ 5 -1  3]
 [ 0  2 -1]
 [-2 -1  0]] 

B= 
 [[ 3  7 -2]
 [ 1  1 -2]
 [ 0  1  3]] 

Det 5.000000000000001
Матрица алгебраических дополнений
 [[-1  2  4]
 [-3  6  7]
 [-5  5 10]]
Транспонированная матрица
 [[-1 -3 -5]
 [ 2  6  5]
 [ 4  7 10]]
Обратная матрица(Вручную)(At*(1/5))
 [[-0.2 -0.6 -1. ]
 [ 0.4  1.2  1. ]
 [ 0.8  1.4  2. ]] 

Обратная матрица (numpy.linalg.inv())
 [[-0.2 -0.6 -1. ]
 [ 0.4  1.2  1. ]
 [ 0.8  1.4  2. ]] 

(Вручную) X= B*A^(-1) 
 [[-1.2 -3.  -1.4]
 [ 2.4  5.  -0.2]
 [ 3.8  9.   1.6]]
X= B*A^(-1) 
 [[-1.2 -3.  -1.4]
 [ 2.4  5.  -0.2]
 [ 3.8  9.   1.6]]

 numpy.linalg.solve().
X= 
 [[-1.2 -3.  -1.4]
 [ 2.4  5.  -0.2]
 [ 3.8  9.   1.6]]


True